fix: cicd (#776)

diff --git a/docker/Dockerfile.ui b/docker/Dockerfile.ui
--- a/docker/Dockerfile.ui
+++ b/docker/Dockerfile.ui
@@ -32,7 +32,6 @@ ENV NEXT_PUBLIC_POSTHOG_HOST https://app.posthog.com
 ENV PUSHER_HOST=localhost
 ENV PUSHER_PORT=6001
 ENV PUSHER_APP_KEY=keepappkey
-ENV GIT_COMMIT_HASH=${GIT_COMMIT_HASH}
 
 # Stop if GIT_COMMIT_HASH is not provided
 RUN if [ -z "$GIT_COMMIT_HASH" ]; then echo "GIT_COMMIT_HASH argument missing" && exit 1; fi
@@ -41,7 +40,12 @@ RUN npm run build
 
 # Production image, copy all the files and run next
 FROM base AS runner
+ARG GIT_COMMIT_HASH
 WORKDIR /app
+# Stop if GIT_COMMIT_HASH is not provided
+ENV GIT_COMMIT_HASH=${GIT_COMMIT_HASH}
+RUN if [ -z "$GIT_COMMIT_HASH" ]; then echo "GIT_COMMIT_HASH argument missing" && exit 1; fi
+
 
 ENV NODE_ENV production
 # Uncomment the following line in case you want to disable telemetry during runtime.
