fix: commit sha (#773)

diff --git a/docker/Dockerfile.ui b/docker/Dockerfile.ui
--- a/docker/Dockerfile.ui
+++ b/docker/Dockerfile.ui
@@ -1,4 +1,4 @@
-ARG GIT_COMMIT_HASH
+
 
 FROM node:18-alpine AS base
 
@@ -15,6 +15,7 @@ RUN npm ci
 
 # Rebuild the source code only when needed
 FROM base AS builder
+ARG GIT_COMMIT_HASH
 WORKDIR /app
 COPY --from=deps /app/node_modules ./node_modules
 COPY . .
@@ -33,6 +34,8 @@ ENV PUSHER_PORT=6001
 ENV PUSHER_APP_KEY=keepappkey
 ENV GIT_COMMIT_HASH=${GIT_COMMIT_HASH}
 
+# Stop if GIT_COMMIT_HASH is not provided
+RUN if [ -z "$GIT_COMMIT_HASH" ]; then echo "GIT_COMMIT_HASH argument missing" && exit 1; fi
 RUN npm run build
 
 
